### ISSUE TITLE
Where can we obtain the training data BNC-100M?

### ISSUE THREAD

**Issue by Yusuke196** [jhlau/acceptability_prediction#1]
In the paper, the following is said.

> Models are trained on the written portion of theBNC, which has approximately 100 million words (henceforth referred  to  as BNC-100M)

However, the BNC dataset I can obtain from the following site mentioned in README.md has roughly 100,000 words (5,250 sentences) only. 
https://gu-clasp.github.io/projects/smog/experiments/

Could anyone tell me where is the 100 million words dataset?

**Comment by jhlau** [comment]
The BNC dataset that you're reading is the annotated BNC data where sentences are annotated with acceptability scores. They are not used for training, but only for evaluation.

The full BNC corpus is here: http://www.natcorp.ox.ac.uk/ (we didn't release the training data, so you'll have to download the raw data and preprocess yourself).

**Comment by Yusuke196** [comment]
I see. Thank you so much.
